### ISSUE TITLE
Pause parameter to not auto play the animation

### ISSUE THREAD

**Issue by serkserk** [fmannhardt/processanimateR#12]
Hi,

I'm creating a Shiny Dashboard around a process map and would like to not automatically play the animation on render, is there curently  any way to achieve that or a posibility to add a parameter otherwise ?

Thanks again for your awesome library !

**Comment by serkserk** [comment]
Thanks for your reply, what I'm actually looking is a way to start an absolute or relative animated process map on a "paused" state so I can toggle the animation after a rendering it.
Your suggestion is fine for small amount of data but it will redraw the process map every time.

**Comment by fmannhardt** [comment]
Should be easy to do, but it will take some time to look into this. If you want to have a go at a pull request, please go ahead. I think adding a parameter to the R code to call the `pauseAnimation()` function in `animation_slider.js` (https://github.com/fmannhardt/processanimateR/blob/master/inst/htmlwidgets/lib/modules/animation_slider.js) would be the way to go. 

Eventually, the pause and unpause methods should be factored out of the slider, but that is a bit more work. Also, it might be needed to reset the SVG time to 0 with `svg.setCurrentTime`.

**Comment by serkserk** [comment]
Thanks, I will see what I can do.

**Comment by fmannhardt** [comment]
Just implemented the feature.

**Comment by serkserk** [comment]
I just had the occasion of testing it only now, it's work great
Thank you a lot !
