### ISSUE TITLE
Error in UseMethod("tbl_vars")

### ISSUE THREAD

**Issue by romanumero** [fmannhardt/processanimateR#3]
Following the getting started instructions results in the error:

Steps
```
source("https://install-github.me/r-lib/remotes")
remotes::install_github("fmannhardt/processanimateR")
library(processanimateR)
library(eventdataR)
data(patients)
animate_process(patients)
```

Error in UseMethod("tbl_vars") : 
  no applicable method for 'tbl_vars' applied to an object of class "NULL"

**Comment by fmannhardt** [comment]
Thanks for the bug report. 

Indeed, the current HEAD version of the master branch relies on a not yet released version of the processmapR package. So you should either use the relesed CRAN versions:

`
install.packages("processanimateR")
`

or also install the development version of processmapR:

`
remotes::install_github("gertjanssenswillen/processmapR")
`

I will update the documentation and @gertjanssenswillen could you release the processmapR version to CRAN?

**Comment by gertjanssenswillen** [comment]
processmapR is on its way to CRAN now
