### ISSUE TITLE
Animation slow and inaccurate in IE and Firefox

### ISSUE THREAD

**Issue by fmannhardt** [fmannhardt/processanimateR#7]
Current v0.2.0 seems to fail to render in IE and Firefox.

**Comment by frkbr** [comment]
Same problem with Safari. In fact, this seems not specific to v0.2.0, but also happens with v0.1.1. in Safari. In Chrome the animation looks good.

**Comment by fmannhardt** [comment]
Thanks for the feedback. I guess it has to do with the fakesmil library that I use to add SMIL support to those browsers. I will try to find out what is wrong. Maybe it is time to go for CSS3 in the future.

**Comment by fmannhardt** [comment]
Could you try with the current development version via:
```

# install the remotes package
source("https://install-github.me/r-lib/remotes")

# use remotes to install the latest version of processanimateR
remotes::install_github("fmannhardt/processanimateR")
```

The Firefox issue should have been solved and I imagine it was the same issue for Safari.

**Comment by frkbr** [comment]
Perfect, now it works with Safari too. Thanks for the fix!
